mvlearn/mvlearn

multiview/embed/utils.py
Add GrasPY citation for these utils. Fixes comments in #30.
=> Adds GrasPY citations in the Zhu-Godsie util file

multiview/embed/gcca.py
Clarification as to Xs input type exactly and switched from Xs shape to Xs length for clarity. Fixes comments in slack.
=> clarified Xs input type and dimensions

docs/README.md
Added information about how to create local html files from the docs/
=> Updated html installation instructions

.travis.yml, mvlearn/embed/__init__.py, mvlearn/embed/dcca.py, mvlearn/embed/splitae.py
Importing without torch fails because it attempts to import files which import torch
=> Fix import

.travis.yml, mvlearn/embed/__init__.py, mvlearn/embed/dcca.py, mvlearn/embed/splitae.py
Torch import error and adds warnings.
Hotfixed on current release (0.0.2) but needed change on master too
=> Hotfix torch import error

.gitattributes, mvlearn/embed/mvmds.py
=> Mvmds Doc Updates

.travis.yml
Add python 3.8 to the list of checked versions in travis.
=> Add python 3.8 to travis ci checks

setup.cfg, setup.py
Add setup.cfg file which ensures LICENSE is included in package.
=> Torch license

mvlearn/embed/splitae.py
Updated the camelCase in SplitAE file to snake_case
=> Fixed Bug #56 "Update SpiltAE internals to snake_case"

mvlearn/embed/gcca.py
Fixes #172  
This fixes some minor errors in the doc strings for the gcca algorithm.
=> Fixing GCCA Doc Strings

mvlearn/plotting/plot.py
Fixes #175 
Fixes above issues. Also sets show as default to False as most of the times people would want to at least save the figure. Seaborn just returns them, no show parameter.
=> Allows crossplots to plot single view

codecov.yml
With this file, a bot will post a comment on PR's to master showing changes in code coverage.
https://docs.codecov.io/docs/pull-request-comments
=> Add codecov.yml file so codecov bot posts PR comment

mvlearn/embed/kcca.py
Make it more clear that linear KCCA is equal to CCA.
Also fixes a rendering issue where reference doesn't render as a link in kcca.
=> Make KCCA docs more clear

mvlearn/semi_supervised/base.py
This PR fixes the BaseCoTrainEstimator docs which had an incorrect Attributes section and some weirdly worded docstrings.
=> Corrected base co-training docstring issues

tests/test_dcca.py
Fixes #190 
Changes the corr threshold for the test to 0 (so it just tests that dcca is able to fit and create a positively correlated output). I feel like this should never fail assuming the algorithm is doing what it's supposed to. 
This also adds a couple tests which increase code coverage.
=> Improved DCCA unit tests

README.md
=> arxiv badge

.github/PULL_REQUEST_TEMPLATE.md, Contributing.md, README.md, docs/contributing.rst, docs/index.rst, docs/install.rst, mvlearn/embed/dcca.py, mvlearn/embed/splitae.py, setup.py
=> update github org

examples/compose/plot_pipeline_sklearn_integration.py, mvlearn/cluster/mv_coreg_spectral.py, mvlearn/cluster/mv_kmeans.py, mvlearn/cluster/mv_spectral.py, mvlearn/compose/rsm.py, mvlearn/datasets/base.py, mvlearn/decomposition/ajive.py, mvlearn/decomposition/groupica.py, mvlearn/decomposition/grouppca.py, mvlearn/decomposition/multiviewica.py, mvlearn/embed/cca.py, mvlearn/embed/dcca.py, mvlearn/embed/gcca.py, mvlearn/embed/kmcca.py, mvlearn/embed/mcca.py, mvlearn/embed/mvmds.py, mvlearn/embed/splitae.py, mvlearn/embed/utils.py, mvlearn/semi_supervised/ctclassifier.py, mvlearn/semi_supervised/ctregression.py
Minor changes and improved consistency, reflecting changes made in the paper itself.
=> Update references for consistency, to match paper edits

docs/install.rst, mvlearn/__init__.py, requirements/base.txt, setup.py, tests/test_ctregressor.py
Adds authors, and updates version number and setup.py in preparation for PyPi update.
=> 0.4.0 changes

setup.py
to have project links in https://pypi.org/project/mvlearn/
=> add project urls

docs/changelog.rst, mvlearn/__init__.py
=> 0.4.1 with graspy optional

README.md, docs/overview.rst
Add a section to Readme and docs Overview pages on citing mvlearn, and change Readme badge from arxiv to jmlr.
=> Readme and docs update with paper

.circleci/config.yml
Fixes #310 
Increases timeout limit from 10m (default) to 30m since the make html command is failing simply because it takes too long to build all the docs.
=> Increase build docs timeout to 30m

docs/README.md, docs/changelog.rst, mvlearn/__init__.py
Increments the version in the __init__.py and updates the changelog to prepare for version 0.5.0 release, given several recent changes to the codebase.
Planning to push a new release to pypi and conda using this version, since the graspy update and other fixes seem worthwhile to have in a new version now
=> increment version and update changelog

setup.py
This is needed for the conda-forge version
=> Explicit requirements for conda version
